### ISSUE TITLE
Medienordner sollte unangetastet bleiben

### ISSUE THREAD

**Issue by skerbis** [WolfgangBusch/media_directories#1]
Hallo Wolfgang,

es wäre sinnvoller einen anderen Ordner dafür zu nutzen, z.B. den Data-Ordner deines AddOns. 
Warum? 
Der Medienordner ist ein REDAXO-System-Ordner und kann seinen Eigenschaften, seine Position und Funktion durch Änderungen am System oder Medienpool verlieren.

**Comment by WolfgangBusch** [comment]
Hallo Thomas,

vielen Dank für die Rückmeldung. Ich habe seit Jahren keine Probleme damit gehabt, Unterordner von media zu nutzen. Wie groß sind die zu erwartenden Probleme wirklich? Können wir dazu mal telefonieren (05333/211461)?

Gruß, Wolfgang,
   Dr. Wolfgang Busch (https://busch-dettum.de/)
